version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - gocritic
    - makezero
    - nilerr
    - prealloc
    - predeclared
    - unconvert
    - unparam
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - unparam
        path: _test\.go
    paths:
      - internal/admin/ui/templates
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
