apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-token-relay-data
  labels:
    app: oauth-token-relay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
